import type { Product } from './types'

export const demoProducts: Product[] = [
  {
    id: 'demo-celestial-mandala',
    slug: 'celestial-mandala',
    name: 'Celestial Mandala',
    subtitle: 'Multi-layered wooden artwork',
    description: 'A precision-cut, multi-layered statement piece designed to create shifting depth and shadow as the light changes.',
    category: 'Mandalas',
    price: 27900000,
    currency: 'NGN',
    images: ['/images/mockup/product-celestial.jpg', '/images/mockup/layers-mandala.jpg'],
    status: 'active',
    stock: 8,
    materials: 'Birch ply, oak veneer, hand-finished edges',
    dimensions: '60 cm, 80 cm, or 100 cm',
  },
  {
    id: 'demo-african-geometry',
    slug: 'african-geometry',
    name: 'African Geometry',
    subtitle: 'Architectural wall art',
    description: 'Layered geometric wall art with a warm natural finish and crisp engraved detailing.',
    category: 'Wall Art',
    price: 19500000,
    currency: 'NGN',
    images: ['/images/mockup/product-african.jpg'],
    status: 'active',
    stock: 6,
  },
  {
    id: 'demo-tree-of-life',
    slug: 'tree-of-life',
    name: 'The Tree of Life',
    subtitle: 'Layered wall art',
    description: 'A sculptural tree design built from precisely aligned wood layers.',
    category: 'Wall Art',
    price: 23500000,
    currency: 'NGN',
    images: ['/images/mockup/product-tree.jpg'],
    status: 'active',
    stock: 5,
  },
  {
    id: 'demo-aurora-lampshade',
    slug: 'aurora-lampshade',
    name: 'Aurora Lampshade',
    subtitle: 'Laser-cut lighting',
    description: 'A warm decorative lampshade designed to cast patterned light across the room.',
    category: 'Lighting',
    price: 26000000,
    currency: 'NGN',
    images: ['/images/mockup/product-lamp.jpg'],
    status: 'active',
    stock: 4,
  },
  {
    id: 'demo-geometric-harmony',
    slug: 'geometric-harmony',
    name: 'Geometric Harmony',
    subtitle: 'Large layered wall piece',
    description: 'A bold geometric centerpiece for contemporary interiors.',
    category: 'Mandalas',
    price: 38000000,
    currency: 'NGN',
    images: ['/images/mockup/product-geometric.jpg'],
    status: 'active',
    stock: 3,
  },
  {
    id: 'demo-heritage-ornament',
    slug: 'heritage-ornament',
    name: 'Heritage Ornament',
    subtitle: 'Precision-cut ornament',
    description: 'A compact decorative piece with detailed laser-cut patterning.',
    category: 'Ornaments',
    price: 6500000,
    currency: 'NGN',
    images: ['/images/mockup/product-heritage.jpg'],
    status: 'active',
    stock: 15,
  },
  {
    id: 'demo-lotus-mandala',
    slug: 'lotus-mandala',
    name: 'Lotus Mandala',
    subtitle: 'Layered floral mandala',
    description: 'A calm, balanced mandala design with layered floral geometry.',
    category: 'Mandalas',
    price: 34000000,
    currency: 'NGN',
    images: ['/images/mockup/product-lotus.jpg'],
    status: 'active',
    stock: 4,
  },
  {
    id: 'demo-bespoke-name-plaque',
    slug: 'bespoke-name-plaque',
    name: 'Bespoke Name Plaque',
    subtitle: 'Personalised wooden plaque',
    description: 'A custom name plaque designed around your lettering, occasion, and finish.',
    category: 'Personalised',
    price: 15000000,
    currency: 'NGN',
    images: ['/images/mockup/product-name-plaque.jpg'],
    status: 'active',
    stock: 10,
  },
]

export function formatMoney(amount: number, currency = 'NGN') {
  return new Intl.NumberFormat('en-NG', {
    style: 'currency',
    currency,
    maximumFractionDigits: 0,
  }).format(amount / 100)
}
